# Generated by Django 3.1.4 on 2020-12-22 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_auto_20201221_1002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_tags', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Создан_им')),
            ],
        ),
        migrations.AddField(
            model_name='notes',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='main.Tags', verbose_name='Тэги'),
        ),
    ]
