# Generated by Django 3.1.4 on 2020-12-23 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201222_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='title_tags',
            new_name='title',
        ),
    ]
