# Generated by Django 3.1.4 on 2020-12-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201223_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='main.Tags', verbose_name='Тэги'),
        ),
    ]
