# Generated by Django 3.1.4 on 2020-12-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201224_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='notes',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='main.Tags', verbose_name='Тэги'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
