# Generated by Django 3.1.4 on 2020-12-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20201224_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='data_birth',
        ),
        migrations.AddField(
            model_name='profile',
            name='date_birth',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
