# Generated by Django 3.1.4 on 2020-12-28 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201228_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='date_birth',
            new_name='daybirth',
        ),
    ]
